[package]
name = "makevcf"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
noodles = { version = "0.94.0", features = ["core", "vcf"] }
anyhow = "1.0.97"